In [1]:
import numpy as np
from tensorflow.keras.models import load_model

# Load your trained LB model
model = load_model("lb_model.h5")

# Layer mapping for 4-6-6-1 model:
# 0 - Dense (input → hidden1)
# 1 - Dropout
# 2 - Dense (hidden1 → hidden2)
# 3 - Dropout
# 4 - Dense (hidden2 → output)

# Extract weights and biases
W1, b1 = model.layers[0].get_weights()  # Input → Hidden Layer 1
W2, b2 = model.layers[2].get_weights()  # Hidden Layer 1 → Hidden Layer 2
W3, b3 = model.layers[4].get_weights()  # Hidden Layer 2 → Output

# Confirm shapes
print("W1 shape:", W1.shape)  # Should be (4,6)
print("b1 shape:", b1.shape)  # Should be (6,)
print("W2 shape:", W2.shape)  # Should be (6,6)
print("b2 shape:", b2.shape)  # Should be (6,)
print("W3 shape:", W3.shape)  # Should be (6,1)
print("b3 shape:", b3.shape)  # Should be (1,)

# Display weights and biases
print("\n--- Input to Hidden Layer 1 ---")
print("Weights (W1):\n", W1)
print("Biases (b1):\n", b1)

print("\n--- Hidden Layer 1 to Hidden Layer 2 ---")
print("Weights (W2):\n", W2)
print("Biases (b2):\n", b2)

print("\n--- Hidden Layer 2 to Output ---")
print("Weights (W3):\n", W3.flatten())
print("Bias (b3):\n", float(b3))

# Optional: Save all to CSV files for reference
np.savetxt("W1_input_to_hidden1.csv", W1, delimiter=",")
np.savetxt("b1_hidden1_bias.csv", b1, delimiter=",")
np.savetxt("W2_hidden1_to_hidden2.csv", W2, delimiter=",")
np.savetxt("b2_hidden2_bias.csv", b2, delimiter=",")
np.savetxt("W3_hidden2_to_output.csv", W3, delimiter=",")
np.savetxt("b3_output_bias.csv", b3, delimiter=",")


W1 shape: (4, 6)
b1 shape: (6,)
W2 shape: (6, 6)
b2 shape: (6,)
W3 shape: (6, 1)
b3 shape: (1,)

--- Input to Hidden Layer 1 ---
Weights (W1):
 [[ 0.01150153 -0.18402337  0.29662016 -0.03355258  0.40678275 -0.24152139]
 [ 0.22766273  0.28722724 -0.20463398 -0.00509284 -0.03708809 -0.35837764]
 [ 0.32391626 -0.3283912  -0.3683454   0.2872654   0.30434     0.4084352 ]
 [ 0.0617235   0.00662541  0.2118065  -0.21334782 -0.33907425  0.20401917]]
Biases (b1):
 [-0.3569844  -0.44550875 -0.42905352 -0.203724    1.0236928  -0.46054736]

--- Hidden Layer 1 to Hidden Layer 2 ---
Weights (W2):
 [[ 0.27658778 -0.44625443 -0.7003487   0.7096354  -0.35786694 -0.4734219 ]
 [-0.3075649   0.6283703   0.63005006  0.44505733  0.4463593  -0.5279042 ]
 [-0.50521344  0.8596433   0.35428768 -0.02691778  0.5149964  -0.9324238 ]
 [ 0.26670456  0.15857366 -0.2393614  -0.487739   -1.1047853   0.3859686 ]
 [-0.09219442  0.04082336  0.42896405 -0.9037849   0.58956623 -0.03950221]
 [-0.09620438  0.44342884 -0.485088

/var/folders/t3/tyl830xn3bz3l5tz9hv_2lzr0000gn/T/ipykernel_7200/3435733303.py:38: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("Bias (b3):\n", float(b3))
